# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: web-electron-capacitor-ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            flags: portable
            extension: exe

          - os: macos-latest
            flags: zip
            extension: zip

          - os: ubuntu-latest
            flags: appimage
            extension: AppImage

    steps:
      - name: Install system dependencies
        run: ${{ matrix.prep }}

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Node dependencies
        run: yarn install

      - name: Build web
        run: yarn build

      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          use_vue_cli: true
          args: ${{ matrix.flags }} --publish never

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.flags }}
          path: dist_electron/primoprod*.${{ matrix.extension }}

  build-capacitor:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Install system dependencies
        run: ${{ matrix.prep }}

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Node dependencies
        run: yarn install

      - name: Build web
        run: yarn build

      - name: Prepare Android build
        run: yarn cap:init

      - name: Android build
        working-directory: ./android
        run: ./gradlew build

      - name: Sign Android build
        run: jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.android/debug.keystore ./android/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Prepare to sign build
        run: mv ./android/app/build/outputs/apk/release/app-release-unsigned.apk ./primoprod.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Android
          path: android/primoprod.apk
