# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            flags: portable
            
          - os: macos-latest
            flags: zip
            
          - os: ubuntu-latest
            flags: appimage
            prep: |
              sudo apt-get install -y wine

    steps:
    - name: Install system dependencies
      run: ${{ matrix.prep }}
      
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install Node dependencies
      run: yarn install
    - name: Build web
      run: yarn build
    
    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with: 
        github_token: ${{ secrets.github_token }}
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        use_vue_cli: true
        args:  ${{ matrix.flags }} --publish always
    
